apiVersion: batch/v1
kind: Job
metadata:
  name: tf-check
  namespace: dev
spec:
  template:
    spec:
      initContainers:
        - name: clone-repo
          image: alpine/git:latest
          command: ["sh", "-c", "rm -rf /workspace/ci-cd-k8s-policy-pipeline && git clone https://github.com/VurumuMahesh15/local-cicd-k8-pipeline.git /workspace/ci-cd-k8s-policy-pipeline"]
          volumeMounts:
            - name: repo
              mountPath: /workspace
      containers:
        - name: policy-check
          image: openpolicyagent/conftest:latest
          workingDir: /workspace/ci-cd-k8s-policy-pipeline/ci-cd-k8s-policy-pipeline
          command: ["sh", "-c", "conftest test terraform/ --policy policy-enforcement/policies"]
          volumeMounts:
            - name: repo
              mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: repo
          hostPath:
            path: /workspace
  backoffLimit: 2
